import {useState} from 'react';
import {startAuthentication,startRegistration} from '@simplewebauthn/browser';
import type {PublicKeyCredentialCreationOptionsJSON,PublicKeyCredentialRequestOptionsJSON} from '@simplewebauthn/browser';
import {KeyRound,ShieldCheck,ArrowRight,Home} from 'lucide-react';
import {api} from './api';
import {ErrorNotice,Field} from './ui';
export function Auth({initialized,onSuccess}:{initialized:boolean;onSuccess:()=>void}){
  const [register,setRegister]=useState(!initialized);const [code,setCode]=useState('');const [name,setName]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  async function access(){if(busy)return;setBusy(true);setError('');try{
    if(register){const r=await api<{options:PublicKeyCredentialCreationOptionsJSON;challengeId:string}>('/auth/register/options',{code});const response=await startRegistration({optionsJSON:r.options});await api('/auth/register/verify',{response,challengeId:r.challengeId,name});}
    else{const r=await api<{options:PublicKeyCredentialRequestOptionsJSON;challengeId:string}>('/auth/login/options',{});const response=await startAuthentication({optionsJSON:r.options});await api('/auth/login/verify',{response,challengeId:r.challengeId});}
    onSuccess();
  }catch(e){setError((e as Error).name==='NotAllowedError'?'La verificación se canceló. Podés volver a intentarlo.':(e as Error).message);}finally{setBusy(false);}}
  return <div className="auth-page"><div className="auth-brand"><span className="brand-mark"><Home/></span><span>Gesell<span className="brand-dot">.</span></span></div><main className="auth-card"><span className="eyebrow">TU DEPARTAMENTO, EN ORDEN</span><h1>{register?'Habilitá este dispositivo':'Todo listo para volver'}</h1><p>{register?'Un paso inicial para que solo tus dispositivos puedan ver las reservas. Después, el acceso queda recordado.':'Usá tu llave de acceso. Sin escribir usuario ni contraseña.'}</p><div className="auth-illustration"><KeyRound size={38}/></div><form onSubmit={e=>{e.preventDefault();void access();}}>{register?<><Field label="Nombre del dispositivo"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Mi iPhone" required minLength={2} maxLength={60} autoComplete="off"/></Field><Field label="Código de habilitación" hint={initialized?'Generalo desde un dispositivo que ya tenga acceso.':'El código inicial se configura al preparar la aplicación.'}><input type="password" value={code} onChange={e=>setCode(e.target.value.trim())} required minLength={16} maxLength={128} autoComplete="off"/></Field></>:null}<ErrorNotice message={error}/><button className="button full" disabled={busy}>{busy?'Verificando…':register?'Habilitar y entrar':'Entrar con mi llave'}<ArrowRight size={18}/></button></form>{initialized?<button className="text-button" onClick={()=>{setRegister(!register);setError('');}}>{register?'Ya tengo una llave de acceso':'Habilitar otro dispositivo'}</button>:null}<div className="auth-foot"><ShieldCheck size={16}/><span>Acceso privado · Sesión recordada hasta 30 días</span></div><p className="muted-text small">En iPhone: Safari → Compartir → Agregar a inicio. La PWA puede pedir una habilitación propia. Si perdés todos los accesos, la recuperación se realiza desde tu cuenta de Cloudflare.</p></main><footer>Administración privada del alquiler temporal</footer></div>;
}
