import {useState} from 'react';
import {ChevronLeft,ChevronRight,Plus,LockKeyhole} from 'lucide-react';
import type {Data,Reservation} from '../shared/domain';
import {PageHeading,Field} from './ui';
import {todayAR} from '../shared/domain';
export function Calendar({data,onOpen,onNew,onBlock}:{data:Data;onOpen:(r:Reservation)=>void;onNew:(date:string)=>void;onBlock:()=>void}){
  const [month,setMonth]=useState('2027-01');const [selected,setSelected]=useState('');
  const [year,mon]=month.split('-').map(Number);const first=new Date(year,mon-1,1);const count=new Date(year,mon,0).getDate();
  const days=Array.from({length:Math.ceil((first.getDay()+count)/7)*7},(_,i)=>{const day=i-first.getDay()+1;return day>0&&day<=count?`${month}-${String(day).padStart(2,'0')}`:null;});
  const active=data.reservations.filter(r=>r.status==='confirmed').sort((a,b)=>a.arrival.localeCompare(b.arrival));const title=new Intl.DateTimeFormat('es-AR',{month:'long',year:'numeric'}).format(first);
  function shift(n:number){const d=new Date(year,mon-1+n,1);setMonth(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`);setSelected('');}
  const selectedStays=active.filter(r=>selected>=r.arrival&&selected<=r.departure);const selectedBlocks=data.blocks.filter(b=>selected>=b.arrival&&selected<b.departure);
  const colors=new Map(active.map((r,i)=>[r.id,i%3]));const guest=(id:string)=>data.guests.find(g=>g.id===id)?.name||'Huésped';
  return <><PageHeading eyebrow="DISPONIBILIDAD" title="Calendario" text="Un mes a la vez. Todas tus fechas, en un solo lugar." actions={<><button className="button secondary" onClick={onBlock}><LockKeyhole size={17}/>Bloquear fechas</button><button className="button" onClick={()=>onNew(selected||month+'-01')}><Plus size={18}/>Nueva reserva</button></>}/><section className="card calendar-card"><div className="calendar-toolbar"><div><span className="eyebrow">DEPARTAMENTO · VILLA GESELL</span><h2 className="month-title">{title}</h2></div><div className="month-controls"><button className="icon-button" aria-label="Mes anterior" onClick={()=>shift(-1)}><ChevronLeft/></button><Field label="Elegir mes"><input type="month" value={month} required min="1900-01" max="2200-12" onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></Field><button className="icon-button" aria-label="Mes siguiente" onClick={()=>shift(1)}><ChevronRight/></button><button className="button secondary today" onClick={()=>{setMonth(todayAR().slice(0,7));setSelected(todayAR());}}>Hoy</button></div></div><div className="calendar-weekdays">{['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'].map(d=><div key={d}>{d}</div>)}</div><div className="calendar-grid">{days.map((date,i)=>{
    const stays=date?active.filter(r=>date>=r.arrival&&date<=r.departure):[];const blocks=date?data.blocks.filter(b=>date>=b.arrival&&date<b.departure):[];
    return <div key={date||'blank'+i} className={'calendar-day '+(!date?'outside ':'')+(date===selected?'selected ':'')+(date===todayAR()?'today-date':'')}>
      {date?<><button className="day-number" onClick={()=>setSelected(date)} aria-label={`Ver ${date}`}>{Number(date.slice(-2))}</button><div className="day-events">{stays.map(r=>{const arrival=date===r.arrival,departure=date===r.departure;return <button key={r.id} className={`stay color-${colors.get(r.id)} ${departure?'departure':''}`} onClick={()=>onOpen(r)} title={`${guest(r.guest_id)} · ${r.arrival} → ${r.departure}`}><span className="event-direction">{arrival?'↘':departure?'↗':'•'}</span><span className="event-name">{departure?'Sale ':arrival?'Entra ':''}{guest(r.guest_id)}</span></button>;})}{blocks.map(b=><button key={b.id} className="stay blocked" onClick={()=>setSelected(date)} title={b.reason}><LockKeyhole size={12}/><span className="event-name">{b.reason}</span></button>)}</div></>:null}</div>;
  })}</div><div className="calendar-legend"><span><i className="legend-color teal"/>Reserva</span><span><i className="legend-color gray"/>Bloqueo</span><span>↘ Ingreso · ↗ Salida</span><p>Se permite salida e ingreso el mismo día.</p></div></section>{selected?<section className="card selected-day"><div className="section-heading"><h3>{new Intl.DateTimeFormat('es-AR',{dateStyle:'full'}).format(new Date(selected+'T12:00:00'))}</h3><button className="button secondary" onClick={()=>onNew(selected)}>Reservar desde este día</button></div>{selectedStays.length||selectedBlocks.length?<div className="day-summary">{selectedStays.map(r=><button className="summary-event" key={r.id} onClick={()=>onOpen(r)}><strong>{guest(r.guest_id)}</strong><span>{selected===r.arrival?`Ingreso · ${r.arrival_time}`:selected===r.departure?`Salida · ${r.departure_time}`:'En estadía'}</span></button>)}{selectedBlocks.map(b=><div className="summary-event" key={b.id}><strong>Bloqueado</strong><span>{b.reason}</span></div>)}</div>:<p className="muted-text">Sin reservas ni bloqueos.</p>}</section>:null}</>;
}
