import {useState} from 'react';
import {UserPlus,CalendarDays,CheckCircle2,AlertCircle} from 'lucide-react';
import type {Data,Guest,Reservation,Mode} from '../shared/domain';
import {calculatePrice,overlaps,money,todayAR} from '../shared/domain';
import {api} from './api';
import {Modal,Form,Field,addDays,pesos} from './ui';
export function ReservationForm({data,reservation,initialDate,onClose,onSaved}:{data:Data;reservation?:Reservation;initialDate?:string;onClose:()=>void;onSaved:(id:string)=>Promise<void>}){
  const arrivalDefault=reservation?.arrival||initialDate||'2027-01-04';
  const rate=data.rates.find(r=>r.effective_from<=arrivalDefault);
  const [guest,setGuest]=useState(reservation?.guest_id||'');const [newGuest,setNewGuest]=useState(false);const [guestName,setGuestName]=useState('');const [phone,setPhone]=useState('');const [guestNotes,setGuestNotes]=useState('');
  const [arrival,setArrival]=useState(arrivalDefault);const [departure,setDeparture]=useState(reservation?.departure||addDays(arrivalDefault,6));
  const [arrivalTime,setArrivalTime]=useState(reservation?.arrival_time||'15:00');const [departureTime,setDepartureTime]=useState(reservation?.departure_time||'10:00');
  const [persons,setPersons]=useState(reservation?.persons||2);const [mode,setMode]=useState<Mode>(reservation?.mode||'week');const [base,setBase]=useState<'week'|'fortnight'>(reservation?.base||'week');
  const [nightly,setNightly]=useState(String((reservation?.nightly??rate?.nightly??0)/100));const [weekly,setWeekly]=useState(String((reservation?.weekly??rate?.weekly??0)/100));
  const [guarantee,setGuarantee]=useState(String((reservation?.guarantee||0)/100));const [notes,setNotes]=useState(reservation?.notes||'');
  let price:ReturnType<typeof calculatePrice>|undefined;let priceError='';try{price=calculatePrice({arrival,departure,mode,base,nightly:pesos(nightly),weekly:pesos(weekly)});}catch(e){priceError=(e as Error).message;}
  const selectedGuest=data.guests.find(g=>g.id===guest);
  const selectedGuestNotes=selectedGuest?.notes??guestNotes;
  const conflict=data.reservations.some(r=>r.id!==reservation?.id&&r.status==='confirmed'&&overlaps(arrival,departure,r.arrival,r.departure))||data.blocks.some(b=>overlaps(arrival,departure,b.arrival,b.departure));
  function setStart(value:string){setArrival(value);if(mode==='week'||mode==='fortnight')setDeparture(addDays(value,mode==='week'?6:13));if(!reservation){const applicable=data.rates.find(r=>r.effective_from<=value);setNightly(String((applicable?.nightly||0)/100));setWeekly(String((applicable?.weekly||0)/100));}}
  function changeMode(v:Mode){setMode(v);if(v==='week'||v==='fortnight')setDeparture(addDays(arrival,v==='week'?6:13));}
  async function save(){if(!price)throw new Error(priceError);if(conflict)throw new Error('Estas fechas se superponen con una reserva o bloqueo.');let guestId=guest;
    if(newGuest){const g=await api<{id:string}>('/guests',{name:guestName,phone,notes:guestNotes});guestId=g.id;setGuest(g.id);setNewGuest(false);}
    if(!guestId)throw new Error('Seleccioná o cargá un huésped.');
    const result=await api<{id:string}>('/reservations',{id:reservation?.id,version:reservation?.version,guest_id:guestId,arrival,departure,arrival_time:arrivalTime,departure_time:departureTime,persons,mode,base,nightly:pesos(nightly),weekly:pesos(weekly),guarantee:pesos(guarantee),notes});await onSaved(result.id);
  }
  return <Modal title={reservation?'Editar reserva':'Nueva reserva'} onClose={onClose} wide><Form onSave={save} label={reservation?'Guardar cambios':'Guardar reserva'} onClose={onClose}>
    <div className="form-section"><h3>Quién se hospeda</h3><div className="guest-picker"><Field label="Huésped"><select value={newGuest?'new':guest} onChange={e=>{setNewGuest(e.target.value==='new');if(e.target.value!=='new')setGuest(e.target.value);}} required><option value="">Seleccionar huésped</option>{data.guests.map(g=><option key={g.id} value={g.id}>{g.name} · {g.notes.trim().replace(/\s+/g,' ')||'Sin observaciones'}</option>)}{guest&&!data.guests.some(g=>g.id===guest)?<option value={guest}>{guestName} · {guestNotes.trim().replace(/\s+/g,' ')||'Sin observaciones'}</option>:null}<option value="new">+ Crear huésped nuevo</option></select></Field><button type="button" className={'button secondary '+(newGuest?'selected':'')} onClick={()=>setNewGuest(!newGuest)}><UserPlus size={17}/>{newGuest?'Usar existente':'Nuevo huésped'}</button></div>{!newGuest&&guest?<div className="guest-identification"><strong>Observaciones del huésped</strong><p className="preserve">{selectedGuestNotes||'Sin observaciones'}</p></div>:null}{newGuest?<div className="form-grid"><Field label="Nombre" hint="Podés ingresar solo el nombre si no conocés el apellido."><input required minLength={2} maxLength={100} value={guestName} onChange={e=>setGuestName(e.target.value)} autoComplete="name"/></Field><Field label="Teléfono"><input required type="tel" minLength={6} maxLength={40} value={phone} onChange={e=>setPhone(e.target.value)} autoComplete="tel"/></Field><Field label="Observaciones del huésped" hint="Para identificarlo; se conserva para sus próximas reservas."><textarea rows={3} maxLength={2000} placeholder="Por ejemplo: el del bar de la esquina" value={guestNotes} onChange={e=>setGuestNotes(e.target.value)}/></Field></div>:null}</div>
    <div className="form-section"><h3>Fechas y personas</h3><div className="form-grid"><Field label="Ingreso"><input type="date" required value={arrival} onChange={e=>setStart(e.target.value)}/></Field><Field label="Horario de ingreso"><input type="time" required value={arrivalTime} onChange={e=>setArrivalTime(e.target.value)}/></Field><Field label="Salida"><input type="date" required min={addDays(arrival,1)} value={departure} onChange={e=>setDeparture(e.target.value)}/></Field><Field label="Horario de salida"><input type="time" required value={departureTime} onChange={e=>setDepartureTime(e.target.value)}/></Field><Field label="Cantidad de personas"><input type="number" min={1} max={20} required value={persons} onChange={e=>setPersons(Number(e.target.value))}/></Field></div></div>
    <div className="form-section"><h3>Precio acordado</h3><div className="segments">{([['night','Noche'],['week','Semana'],['fortnight','Quincena'],['combined','Combinada']] as [Mode,string][]).map(([v,l])=><button type="button" key={v} className={mode===v?'active':''} onClick={()=>changeMode(v)}>{l}</button>)}</div>{mode==='combined'?<Field label="Paquete base"><select value={base} onChange={e=>setBase(e.target.value as typeof base)}><option value="week">Semana · 6 noches</option><option value="fortnight">Quincena · 13 noches</option></select></Field>:null}<div className="form-grid"><Field label="Tarifa por noche ($)"><input type="number" min={0} max={100000000} step="0.01" required value={nightly} onChange={e=>setNightly(e.target.value)}/></Field><Field label="Tarifa semanal ($)"><input type="number" min={0} max={100000000} step="0.01" required value={weekly} onChange={e=>setWeekly(e.target.value)}/></Field></div><p className="muted-text small">Semana: 6 noches a precio fijo. Quincena: 13 noches a dos tarifas semanales. Puede comenzar cualquier día.</p><div className="price-preview"><div><span>{price?`${price.nights} noches · ${price.description}`:priceError}</span><strong>{price?money(price.total):'Revisá el cálculo'}</strong></div><CalendarDays size={30}/></div>{price?<div className={'availability '+(conflict?'conflict':'')}>{conflict?<AlertCircle size={17}/>:<CheckCircle2 size={17}/>} {conflict?'Hay una superposición de fechas':'Fechas disponibles'}<small>La salida y el siguiente ingreso pueden coincidir el mismo día.</small></div>:null}</div>
    <div className="form-grid"><Field label="Garantía acordada ($)" hint="Separada del alquiler; no cambia el total."><input type="number" min={0} max={100000000} step="0.01" required value={guarantee} onChange={e=>setGuarantee(e.target.value)}/></Field><Field label="Observaciones"><textarea rows={3} maxLength={3000} value={notes} onChange={e=>setNotes(e.target.value)}/></Field></div>
  </Form></Modal>;
}
export function GuestForm({guest,onClose,onSaved}:{guest?:Guest;onClose:()=>void;onSaved:()=>Promise<void>}){
  const [name,setName]=useState(guest?.name||'');const [phone,setPhone]=useState(guest?.phone||'');const [notes,setNotes]=useState(guest?.notes||'');
  return <Modal title={guest?'Editar huésped':'Nuevo huésped'} onClose={onClose}><Form onClose={onClose} onSave={async()=>{await api('/guests',{id:guest?.id,name,phone,notes});await onSaved();}}><Field label="Nombre" hint="Podés ingresar solo el nombre si no conocés el apellido."><input required minLength={2} maxLength={100} value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></Field><Field label="Teléfono"><input required type="tel" minLength={6} maxLength={40} value={phone} onChange={e=>setPhone(e.target.value)} autoComplete="tel"/></Field><Field label="Observaciones" hint="Para identificarlo; por ejemplo: el del bar de la esquina."><textarea rows={4} maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)}/></Field><p className="muted-text small">Podrás seleccionar esta persona al crear cualquier reserva.</p></Form></Modal>;
}
export function BlockForm({initialDate,onClose,onSaved}:{initialDate?:string;onClose:()=>void;onSaved:()=>Promise<void>}){
  const [arrival,setArrival]=useState(initialDate||todayAR());const [departure,setDeparture]=useState(addDays(initialDate||todayAR(),1));const [reason,setReason]=useState('');
  return <Modal title="Bloquear fechas" onClose={onClose}><Form label="Guardar bloqueo" onClose={onClose} onSave={async()=>{await api('/blocks',{arrival,departure,reason});await onSaved();}}><div className="form-grid"><Field label="Desde"><input type="date" required value={arrival} onChange={e=>setArrival(e.target.value)}/></Field><Field label="Hasta (fecha liberada)"><input type="date" min={addDays(arrival,1)} required value={departure} onChange={e=>setDeparture(e.target.value)}/></Field></div><Field label="Motivo"><input required minLength={2} maxLength={200} placeholder="Uso propio, mantenimiento…" value={reason} onChange={e=>setReason(e.target.value)}/></Field><p className="muted-text small">El día de fin queda disponible para un nuevo ingreso. Un bloqueo no puede superponerse con una reserva.</p></Form></Modal>;
}
