import {useEffect,useState} from 'react';
import {Pencil,ArrowLeft,Phone,Users,CalendarDays,Wallet,ShieldCheck,Plus,Ban,Clock3} from 'lucide-react';
import type {Data,Reservation,Payment} from '../shared/domain';
import {balance,money,calculatePrice,calculateAutomaticPrice,todayAR} from '../shared/domain';
import {Modal,Form,Field,Status,shortDate,localTimestamp,pesos,Empty} from './ui';
import {api} from './api';
const paymentLabels:Record<Payment['kind'],string>={rent:'Pago de alquiler',deposit:'Garantía recibida',deposit_refund:'Devolución de garantía',rent_refund:'Devolución de alquiler'};
export function ReservationDetail({reservation:r,data,onBack,onEdit,onRefresh}:{reservation:Reservation;data:Data;onBack:()=>void;onEdit:()=>void;onRefresh:()=>Promise<void>}){
  const [paymentOpen,setPaymentOpen]=useState(false);const [cancelOpen,setCancelOpen]=useState(false);const [history,setHistory]=useState<{action:string;previous:string|null;created_at:string}[]>([]);const [historyError,setHistoryError]=useState('');
  const guest=data.guests.find(g=>g.id===r.guest_id);const values=balance(r,data.payments);const entries=data.payments.filter(p=>p.reservation_id===r.id);const price=(()=>{try{return calculatePrice(r);}catch{return calculateAutomaticPrice(r);}})();
  useEffect(()=>{let active=true;api<typeof history>('/history?id='+r.id).then(v=>{if(active)setHistory(v);}).catch(()=>{if(active)setHistoryError('No se pudo cargar el historial.');});return()=>{active=false;};},[r.id,r.version]);
  return <><button className="back-button" onClick={onBack}><ArrowLeft size={17}/>Volver a reservas</button><header className="page-heading"><div><span className="eyebrow">FICHA DE RESERVA</span><h1>{guest?.name||'Huésped'}</h1><p className="reservation-guest-contact"><Phone size={14}/><span>{guest?.phone} · {r.persons} persona{r.persons===1?'':'s'}</span></p><p className="preserve reservation-guest-identification">{guest?.notes||'Sin observaciones del huésped.'}</p></div><div className="heading-actions"><Status cancelled={r.status==='cancelled'}/>{r.status==='confirmed'?<button className="button secondary" onClick={onEdit}><Pencil size={17}/>Editar reserva</button>:null}</div></header>
    <section className="card stay-overview"><div className="overview-item"><CalendarDays/><span>Ingreso<strong>{shortDate(r.arrival)}</strong><small>{r.arrival_time} h</small></span></div><div className="overview-item"><CalendarDays/><span>Salida<strong>{shortDate(r.departure)}</strong><small>{r.departure_time} h</small></span></div><div className="overview-item"><Users/><span>Estadía<strong>{price.nights} noches</strong><small>{price.description}</small></span></div><div className="overview-item"><Wallet/><span>Total acordado<strong className="teal-text">{money(r.total)}</strong><small>Garantía por separado</small></span></div></section>
    {r.status==='cancelled'?<div className="cancelled-notice"><Ban size={18}/><div><strong>Reserva cancelada · Fechas liberadas</strong><p>{r.cancellation_reason}</p><small>Los cobros se conservan. Las devoluciones deben registrarse por separado.</small></div></div>:null}
    <div className="detail-grid"><section className="card"><div className="section-heading"><h2>Pagos y devoluciones</h2><button className="button" onClick={()=>setPaymentOpen(true)}><Plus size={17}/>{r.status==='cancelled'?'Registrar devolución':'Registrar movimiento'}</button></div><div className="balance-row"><div><span>Alquiler cobrado neto</span><strong>{money(values.rent)}</strong></div><div><span>{r.status==='cancelled'?'Diferencia con total original':'Saldo pendiente'}</span><strong className="amber-text">{money(values.pending)}</strong></div></div>{entries.length?<div className="payment-list">{entries.map(p=><div className="payment-row" key={p.id}><div className={'payment-symbol '+(p.kind.includes('refund')?'refund':'')}><Wallet size={16}/></div><div><strong>{paymentLabels[p.kind]}</strong><span>{shortDate(p.date)} · {p.method}{p.notes?` · ${p.notes}`:''}</span></div><strong className={p.kind.includes('refund')?'amber-text':''}>{p.kind.includes('refund')?'− ':''}{money(p.amount)}</strong></div>)}</div>:<Empty title="Todavía no hay movimientos" text="Registrá la seña o el primer pago cuando lo recibas."/>}</section><section className="card guarantee-card"><ShieldCheck size={28}/><h2>Garantía</h2><div className="guarantee-amount">{money(r.guarantee)}</div><p className="muted-text">Importe acordado</p><div className="guarantee-line"><span>En tu poder</span><strong>{money(values.deposit)}</strong></div><p className="small muted-text">Registrá lo recibido y cada devolución, total o parcial. Este importe no forma parte del alquiler.</p></section></div>
    <div className="detail-grid"><section className="card"><h2>Observaciones de la reserva</h2><p className="preserve">{r.notes||'Sin observaciones.'}</p></section><section className="card"><h2><Clock3 size={18}/> Historial de cambios</h2><p className="small muted-text">Reserva creada: {localTimestamp(r.created_at)}</p>{history.map((h,i)=><div key={i} className="history-row"><strong>{h.action==='cancel'?'Cancelación':'Edición de reserva'}</strong><span>{localTimestamp(h.created_at)}</span>{h.previous?<small>Antes: {historyDescription(h.previous)}</small>:null}</div>)}{historyError?<p className="muted-text">{historyError}</p>:null}{!history.length&&!historyError?<p className="muted-text small">Sin modificaciones posteriores.</p>:null}</section></div>
    {r.status==='confirmed'?<div className="danger-zone"><p>Cancelar conserva la ficha y todos sus pagos, y libera las fechas.</p><button className="button danger-outline" onClick={()=>setCancelOpen(true)}><Ban size={16}/>Cancelar reserva</button></div>:null}
    {paymentOpen?<PaymentForm reservation={r} data={data} onClose={()=>setPaymentOpen(false)} onSaved={async()=>{await onRefresh();setPaymentOpen(false);}}/>:null}
    {cancelOpen?<CancelForm reservation={r} onClose={()=>setCancelOpen(false)} onSaved={async()=>{await onRefresh();setCancelOpen(false);}}/>:null}
  </>;
}
function historyDescription(v:string){try{const h=JSON.parse(v);return `${shortDate(h.arrival)} → ${shortDate(h.departure)} · ${money(h.total)}`;}catch{return 'Datos anteriores guardados';}}
function PaymentForm({reservation:r,data,onClose,onSaved}:{reservation:Reservation;data:Data;onClose:()=>void;onSaved:()=>Promise<void>}){
  const [id]=useState(()=>crypto.randomUUID());const [kind,setKind]=useState<Payment['kind']>(r.status==='cancelled'?'rent_refund':'rent');const [amount,setAmount]=useState('');const [date,setDate]=useState(todayAR());const [method,setMethod]=useState('Transferencia');const [notes,setNotes]=useState('');const values=balance(r,data.payments);
  const limit=kind==='rent'?values.pending:kind==='deposit'?r.guarantee-values.deposit:kind==='deposit_refund'?values.deposit:values.rent;
  return <Modal title="Registrar movimiento" onClose={onClose}><Form onClose={onClose} label="Registrar movimiento" onSave={async()=>{await api('/payments',{id,reservation_id:r.id,kind,amount:pesos(amount),date,method,notes});await onSaved();}}><Field label="Tipo de movimiento"><select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}>{Object.entries(paymentLabels).filter(([k])=>r.status==='confirmed'||k.includes('refund')).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></Field><div className="form-grid"><Field label="Importe ($)" hint={`Máximo: ${money(limit)}`}><input autoFocus required type="number" min="0.01" max={limit/100} step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></Field><Field label="Fecha"><input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></Field></div><Field label="Medio de pago"><select value={method} onChange={e=>setMethod(e.target.value)}><option>Transferencia</option><option>Efectivo</option><option>Otro</option></select></Field><Field label="Observaciones"><textarea maxLength={1000} rows={3} placeholder="Seña, cuota, motivo de devolución…" value={notes} onChange={e=>setNotes(e.target.value)}/></Field><p className="muted-text small">Solo registra un movimiento ya realizado. La aplicación no cobra ni transfiere dinero.</p></Form></Modal>;
}
function CancelForm({reservation:r,onClose,onSaved}:{reservation:Reservation;onClose:()=>void;onSaved:()=>Promise<void>}){
  const [reason,setReason]=useState('');return <Modal title="Cancelar reserva" onClose={onClose}><Form label="Confirmar cancelación" onClose={onClose} onSave={async()=>{await api('/reservations/cancel',{id:r.id,version:r.version,reason});await onSaved();}}><p>Se liberarán las fechas. La ficha, el huésped y los pagos permanecerán en el historial.</p><Field label="Motivo"><textarea autoFocus required minLength={3} maxLength={1000} rows={4} value={reason} onChange={e=>setReason(e.target.value)}/></Field><p className="muted-text small">Esta acción no registra devoluciones automáticamente.</p></Form></Modal>;
}
